### ISSUE TITLE
Compatibility with moodle 4.1

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [catalyst/moodle_tool_blocksmanager#28] opened 2023-02-23 16:47 UTC
We have installed the block manager plugin on a server running Moodle 4.1.1 to do some testing of the plugin's compatibility with Moodle 4.1. The plugin is not work as expected on Moodle 4.1, we are able to configure new blocks to be added to courses but when clicking the 'Apply set of blocks' button to trigger the adhoc task to add the blocks to courses the task fails. 

I have added some code to the plugin to work out what the issue is. The output of this is below. It appears that once the flow of the update process gets to the cache clearing steps in modinfolib.php the code is expecting a different class of object to what it recieves. When comparing the modinfo.php files between Moodle 3.11 (where we have the plugin working) and Moodle 4.1 the file is about 300 lines longer. So I assume the code changes are cause the issue.

Debug ouput as follows - 
`ABOUT TO CREATE ALL BLOCK INSTANCES... used 29 dbqueries
... used 0.39251804351807 seconds
Adhoc task failed: tool_blocksmanager\task\apply_blocks_set_up,Argument 1 passed to course_modinfo::build_course_cache() must be an instance of stdClass, instance of core_course_list_element given, called in /Sites/localhost/moodle4/lib/modinfolib.php on line 484
Backtrace:
* line 484 of /lib/modinfolib.php: call to course_modinfo::build_course_cache()
* line 436 of /lib/modinfolib.php: call to course_modinfo->__construct()
* line 2538 of /lib/modinfolib.php: call to course_modinfo::instance()
* line 184 of /blocks/glossary_random/block_glossary_random.php: call to get_fast_modinfo()
* line 67 of /blocks/glossary_random/block_glossary_random.php: call to block_glossary_random->get_glossary_cm()
* line 474 of /blocks/moodleblock.class.php: call to block_glossary_random->specialization()
* line 2099 of /lib/blocklib.php: call to block_base->_load_instance()
* line 1097 of /lib/blocklib.php: call to block_instance()
* line 1258 of /lib/blocklib.php: call to block_manager->create_block_instances()
* line 1145 of /lib/blocklib.php: call to block_manager->ensure_instances_exist()
* line 90 of /admin/tool/blocksmanager/classes/setup_item_processor.php: call to block_manager->create_all_block_instances()
* line 53 of /admin/tool/blocksmanager/classes/setup_item_processor.php: call to tool_blocksmanager\setup_item_processor->process()
* line 55 of /admin/tool/blocksmanager/classes/task/apply_blocks_set_up.php: call to tool_blocksmanager\setup_item_processor->process_bulk()
* line 359 of /lib/cronlib.php: call to tool_blocksmanager\task\apply_blocks_set_up->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()`

Happy to supply additional debugging information if it will help to diagnose the issue.

**Comment by dmitriim** [comment] 2023-02-23 21:25
Thanks for reporting this @james-pearce-bath-ac!

After a quick look at the backtrace, it seems like the problem is in build_course_cache method that after https://tracker.moodle.org/browse/MDL-72991 casts $course parameter to be stdClass. 

In our code here https://github.com/catalyst/moodle_tool_blocksmanager/blob/master/classes/setup_item_processor.php#L69 we build a list of courses that are core_course_list_element type. 

In theory as the tracker landed to 3.11 it shouldn't work in 3.11 version, but, I haven't really checked what's in 3.11 codebase. 

Not sure is getting the plugin ready for 4.1 is in our radar at this stage. Sol PR is welcome.

If you need this to be fixed urgently, please contact our sales team https://catalyst-au.net/contact-us

**Comment by dmitriim** [comment] 2023-02-23 21:37
I also created https://tracker.moodle.org/browse/MDL-77397

**Comment by sarahjcotton** [comment] 2023-03-29 16:13
Hi @james-pearce-bath-ac I've done some testing with the current master branch of blocks manager and the 20230116 build of Moodle 4.1 and I'm not getting any errors with the adhoc task when  manipulating the badges block (see output below). That said, I had a local fix for issue #29 so I don't know if that was enough to resolve the issue. I'll create PR for that now so you can test that out, but otherwise it might be helpful if you can share the exact config you're adding so we can see if it's related to another block, especially as we've previously found conflicts with the multiblock.

```
Execute adhoc task: tool_blocksmanager\task\apply_blocks_set_up
Adhoc task id: 11
Adhoc task custom data: side-pre||1||badges||3||1||1||||0||side-pre||3||0||course-view-*

... started 16:58:15. Current memory use 19.1 MB.
Changed position of badges in course 2
... used 14 dbqueries
... used 0.086750030517578 seconds
Adhoc task complete: tool_blocksmanager\task\apply_blocks_set_up
Ran 2 adhoc tasks found at Wed, 29 Mar 2023 16:58:15 +0100
```

**Comment by james-pearce-bath-ac** [comment] 2023-04-12 16:18
Thanks for the work done on this issue. I have pulled the latest master code for the plugin and deployed it to our test site running 4.1.1 and still have the same issue with the course cache clearing. Here is the output of the task log -

Execute adhoc task: tool_blocksmanager\task\apply_blocks_set_up
Adhoc task id: 367
Adhoc task custom data: side-pre||2||activity_modules||-10||1||1||||0||side-pre||-10||0||course-view-*
side-pre||2||samis||-9||1||1||||0||side-pre||-9||0||course-view-*
side-pre||2||panopto||-8||1||1||||0||side-pre||-8||0||course-view-*

... started 16:56:02. Current memory use 36.5 MB.
Changed position of activity_modules in course 138
Changed position of activity_modules in course 137
Changed position of activity_modules in course 120
Changed position of activity_modules in course 73
Changed position of activity_modules in course 51
Changed position of activity_modules in course 50
Changed position of activity_modules in course 32
Changed position of activity_modules in course 45
Changed position of activity_modules in course 44
... used 110 dbqueries
... used 0.12372303009033 seconds
Adhoc task failed: tool_blocksmanager\task\apply_blocks_set_up,Argument 1 passed to course_modinfo::build_course_cache() must be an instance of stdClass, instance of core_course_list_element given, called in /var/www/html/moodle41/lib/modinfolib.php on line 478
Backtrace:
* line 478 of /lib/modinfolib.php: call to course_modinfo::build_course_cache()
* line 436 of /lib/modinfolib.php: call to course_modinfo->__construct()
* line 2532 of /lib/modinfolib.php: call to course_modinfo::instance()
* line 184 of /blocks/glossary_random/block_glossary_random.php: call to get_fast_modinfo()
* line 67 of /blocks/glossary_random/block_glossary_random.php: call to block_glossary_random->get_glossary_cm()
* line 474 of /blocks/moodleblock.class.php: call to block_glossary_random->specialization()
* line 2099 of /lib/blocklib.php: call to block_base->_load_instance()
* line 1097 of /lib/blocklib.php: call to block_instance()
* line 1258 of /lib/blocklib.php: call to block_manager->create_block_instances()
* line 1145 of /lib/blocklib.php: call to block_manager->ensure_instances_exist()
* line 88 of /admin/tool/blocksmanager/classes/setup_item_processor.php: call to block_manager->create_all_block_instances()
* line 52 of /admin/tool/blocksmanager/classes/setup_item_processor.php: call to tool_blocksmanager\setup_item_processor->process()
* line 55 of /admin/tool/blocksmanager/classes/task/apply_blocks_set_up.php: call to tool_blocksmanager\setup_item_processor->process_bulk()
* line 359 of /lib/cronlib.php: call to tool_blocksmanager\task\apply_blocks_set_up->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()

It appears to be working when changing positions of the block but failing when rebuilding the course cache.

**Comment by dmitriim** [comment] 2023-05-05 07:14
I can confirm that the block works in 4.1 and I could replicate the issue glossary_random in 4.1

The patch is here https://github.com/catalyst/moodle_tool_blocksmanager/pull/40 

@sarahjcotton if you can have a look that would be awesome.

**Comment by dmitriim** [comment] 2023-05-05 23:58
I believe everything should be working now. Closing...

**Closed by dmitriim** 2023-05-05 23:58 UTC
Labels: enhancement
