### ISSUE TITLE
Error message in Moodle 4.1.1

### ISSUE THREAD

**Issue by cdipe** [catalyst/moodle_tool_blocksmanager#29] opened 2023-03-16 09:53 UTC
We installed it on our full Preview server, with Moodle 4.1.1 (Build: 20230116, as on our MAMP installation). It didn't work there. The page didn't respond.
The error in the log:
Fatal error: Declaration of tool_blocksmanager\block_manager::add_block_at_end_of_default_region($blockname) must be compatible with block_manager::add_block_at_end_of_default_region($blockname, $blockregion = null) in /var/www/html/moodle311/admin/tool/blocksmanager/classes/block_manager.php on line 334

(Please see MUA conversation, https://moodleassociation.org/mod/forum/discuss.php?d=1158)

**Comment by dmitriim** [comment] 2023-03-16 12:34
I'll close this one as a duplicate of https://github.com/catalyst/moodle_tool_blocksmanager/issues/28

**Closed by dmitriim** 2023-03-16 12:34 UTC

**Comment by danmarsden** [comment] 2023-03-16 20:05
Thanks @dmitriim - I sugggested the reporter in the MUA forums create a separate issue as the errors seemed different #28 appeared to be happening in the tasks where as this one is happeining in the main ui - but I see you've copied the errors into the other one too :-)

**Comment by dmitriim** [comment] 2023-03-16 22:04
Sorry @danmarsden
I thought we could have all 4.1 related issues in one place so we solve them all at once.
